name: Build and upload

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Package release 
        run: zip -r "release-artifact.zip" *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: "release-artifact.zip"
          retention-days: 1
          overwrite: true
